name: build

on:
  push:
  release:
    types: [published]
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout_code

      - name: Download DirectX sadness
        shell: bash
        run: curl -LO https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe

      - name: Install DirectX sadness
        run: |
          .\DXSDK_Jun10.exe /F /U
          $app = Get-Process DXSDK_Jun10
          Wait-Process $app.Id
          $global:LASTEXITCODE = 0

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        id: setup_msbuild

      - name: Run build script
        id: run_msbuild
        shell: bash
        run: ./build.sh

      - name: Run package script
        id: package
        shell: bash
        run: |
          export VERSION=0.0.1
          [ "${GITHUB_REF_TYPE}" == "tag" ] && VERSION="${GITHUB_REF_NAME##*v}"
          ./package.sh
          installer_path=build/mirrors-edge-multiplayer-${VERSION}.exe
          echo "installer_path=${installer_path}" >> "${GITHUB_OUTPUT}"
          echo "installer_name=${installer_path##*/}" >> "${GITHUB_OUTPUT}"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package.outputs.installer_name}}
          path: ${{ steps.package.outputs.installer_path}}
          if-no-files-found: error

      - uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.package.outputs.installer_path}}
          asset_name: ${{ steps.package.outputs.installer_name}}
          asset_content_type: 'application/x-tar'
